import { useState } from 'react'
import { Copy, Link2, Medal, Share2, Swords, Target } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Badge, Button, Card, Field, fieldClass } from '../components/ui'
import { useApp } from '../context/AppContext'
import { addActivity, getStats, readiness } from '../lib/platform'
import usePageMeta from '../lib/usePageMeta'
export default function ChallengesPage(){
 usePageMeta('Challenges — PrepKite','Focused interview drills built around your target role and skills.')
 const {user,profile,toast}=useApp();const nav=useNavigate();const [title,setTitle]=useState('My interview challenge');const [created,setCreated]=useState('');if(!user||!profile)return null
 const r=readiness(user.id),s=getStats(user.id),weak=r.skills.slice().sort((a,b)=>a.value-b.value).slice(0,3);const cards=[{title:'Weak-skill sprint',type:'Technical',prompt:`Complete three ${weak[0]?.skill||'core skill'} tasks and explain your reasoning.`},{title:'Project pressure test',type:'Project',prompt:'Give a 90-second project story, then defend one technical or business trade-off.'},{title:'60-second interview',type:'Communication',prompt:`Introduce yourself for ${profile.role} and connect your background to ${profile.company||'the target role'}.`}]
 const create=()=>{const slug=(title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'interview-challenge')+'-'+Date.now().toString(36);const link=`${window.location.origin}${window.location.pathname}#/challenges?challenge=${slug}`;setCreated(link);addActivity(user.id,{type:'practice',label:`Created challenge: ${title}`});toast({title:'Challenge link created',description:'This release creates a local challenge URL. A shared participant database can be connected later.',variant:'success'})}
 const copy=async()=>{try{await navigator.clipboard.writeText(created);toast({title:'Link copied',variant:'success'})}catch{toast({title:'Copy blocked',description:'Select the link and copy it manually.',variant:'error'})}}
 return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div><p className="section-kicker">Focused challenges</p><h1 className="display-font mt-2 text-4xl font-semibold">Turn your weak areas into short interview drills.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Challenges are generated from your current preparation context. They are practice tools, not hiring scores or community rankings.</p></div><div className="mt-7 grid gap-4 md:grid-cols-3">{cards.map(c=><Card key={c.title}><div className="flex justify-between"><Badge>{c.type}</Badge><Swords size={18}/></div><h2 className="mt-4 text-lg font-extrabold">{c.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{c.prompt}</p><Button className="mt-5 w-full" variant="outline" onClick={()=>nav('/mock')}>Start drill</Button></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card className="bg-primary text-primary-foreground"><div className="flex gap-3"><Medal size={20}/><div><p className="text-xs font-black uppercase tracking-[.13em] text-primary-foreground/70">Your current signal</p><p className="display-font mt-2 text-6xl font-semibold">{r.score}%</p></div></div><p className="mt-4 text-sm leading-6 text-primary-foreground/75">{s.weeklyCount} preparation actions this week. Next focus: {weak[0]?.skill||'start your first practice'}.</p></Card><Card><div className="flex items-center gap-3"><span className="rounded-lg bg-accent p-2 text-secondary"><Share2 size={19}/></span><div><p className="section-kicker">Create a drill</p><h2 className="text-lg font-extrabold">Invite a friend or save a challenge link</h2></div></div><Field label="Challenge title" htmlFor="challenge-title"><input id="challenge-title" value={title} onChange={e=>setTitle(e.target.value)} className={`${fieldClass} mt-4`}/></Field><Button onClick={create} className="mt-4"><Link2 size={16}/> Create link</Button>{created&&<div className="mt-5 rounded-xl border border-border bg-muted/50 p-4"><p className="text-sm font-extrabold">Local challenge URL</p><p className="mt-2 break-all text-xs text-muted-foreground">{created}</p><Button variant="outline" className="mt-3" onClick={copy}><Copy size={15}/> Copy</Button></div>}<div className="mt-5 flex gap-3 rounded-lg bg-muted/60 p-4 text-xs leading-5 text-muted-foreground"><Target size={17} className="shrink-0"/>For true cross-user challenges, the next backend version should store challenge IDs, participants and results server-side.</div></Card></div></div>
}
