import { useMemo } from 'react'
import { ArrowRight, BrainCircuit, CalendarCheck2, CheckCircle2, Flame, Target, TrendingUp, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge, Button, Card } from '../components/ui'
import { useApp } from '../context/AppContext'
import { addActivity, attendanceToday, getQuestionBank, getStats, markAttendance, readiness } from '../lib/platform'
import usePageMeta from '../lib/usePageMeta'
export default function DashboardPage(){
 usePageMeta('Dashboard — PrepKite','Personalized interview preparation dashboard.')
 const {user,profile,toast}=useApp(); if(!user||!profile)return null
 const stats=getStats(user.id), ready=readiness(user.id), bank=getQuestionBank(profile), attended=attendanceToday(user.id)
 const weak=ready.skills.slice().sort((a,b)=>a.value-b.value).slice(0,3), strong=ready.skills.slice().sort((a,b)=>b.value-a.value).slice(0,3)
 const top=bank.filter(q=>q.category==='Practical').slice(0,3)
 const attend=()=>{markAttendance(user.id);toast({title:'Attendance marked',description:'Today counts toward your preparation streak.',variant:'success'})}
 return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
  <div className="rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">Your interview command center</p><h1 className="display-font mt-2 text-4xl font-semibold sm:text-5xl">Build your next interview around <span className="text-secondary">you.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{profile.name}, you are preparing for <b className="text-foreground">{profile.role}</b>{profile.company?<> at <b className="text-foreground">{profile.company}</b></>:'. Choose a company to unlock company-focused practice.'}</p></div><div className="flex flex-wrap gap-2"><Link to="/onboarding"><Button variant="outline">Edit context</Button></Link><Link to="/mock"><Button>Start mock interview <ArrowRight size={16}/></Button></Link></div></div></div>
  <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Target} label="Readiness" value={`${ready.score}%`} note="Based on recent activity"/><Metric icon={TrendingUp} label="This week" value={`${stats.weeklyCount}`} note="Preparation actions"/><Metric icon={CalendarCheck2} label="Attendance" value={`${stats.attendanceDays}`} note={`${stats.streak} day current streak`}/><Metric icon={Trophy} label="XP" value={`${stats.xp}`} note="Earned from practice"/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
   <Card><div className="flex items-center justify-between"><div><p className="section-kicker">Today’s interview plan</p><h2 className="mt-1 text-xl font-extrabold">A focused session, not random practice.</h2></div>{attended?<Badge tone="success"><CheckCircle2 size={13} className="mr-1"/> Attended</Badge>:<Button variant="outline" onClick={attend}><CalendarCheck2 size={15}/> Mark attendance</Button>}</div><div className="mt-5 grid gap-3 md:grid-cols-2"><Plan n="01" title={`${profile.role} practicals`} desc={`${top[0]?.skill||'Core skill'} · 3 realistic tasks`} to="/practice"/><Plan n="02" title="Company question patterns" desc={profile.company?`${profile.company} · reported themes + practice`: 'Choose a company first'} to="/companies"/><Plan n="03" title="Project follow-ups" desc={profile.projects.length?`${profile.projects.length} project${profile.projects.length>1?'s':''} in your profile`:'Add a project to unlock follow-ups'} to="/onboarding"/><Plan n="04" title="15-minute mock" desc="Technical + behavioral + follow-up" to="/mock"/></div></Card>
   <Card><p className="section-kicker">Your signal</p><h2 className="mt-1 text-xl font-extrabold">What to improve next</h2><div className="mt-5 space-y-4">{weak.map(s=><div key={s.skill}><div className="flex justify-between text-sm"><span className="font-bold">{s.skill}</span><span>{s.value}%</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-secondary" style={{width:`${s.value}%`}}/></div></div>)}<div className="rounded-lg bg-accent/60 p-4 text-sm leading-6"><b>Strong signals:</b> {strong.map(s=>s.skill).join(', ')}. Keep them warm while you work on the lower scores.</div></div></Card>
  </div>
  <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><div className="flex items-center gap-2"><BrainCircuit size={20}/><h2 className="text-lg font-extrabold">Top practical questions</h2></div><div className="mt-4 space-y-3">{top.map((q,i)=><Link key={q.id} to={`/questions?open=${encodeURIComponent(q.id)}`} className="focus-ring block rounded-lg border border-border p-4 hover:bg-muted/50"><div className="flex gap-3"><span className="font-extrabold text-secondary">0{i+1}</span><div><p className="font-bold">{q.title}</p><p className="mt-1 text-sm text-muted-foreground">{q.skill} · {q.category}</p></div></div></Link>)}</div></Card><Card><div className="flex items-center gap-2"><Flame size={20}/><h2 className="text-lg font-extrabold">Recent preparation</h2></div><div className="mt-4 space-y-3">{stats.activities.slice(0,5).map(a=><div key={a.id} className="flex items-start justify-between border-b border-border pb-3 last:border-0"><div><p className="text-sm font-bold">{a.label}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(a.timestamp).toLocaleString()}</p></div>{typeof a.score==='number'&&<Badge tone={a.score>=80?'success':'warning'}>{a.score}%</Badge>}</div>)}{!stats.activities.length&&<p className="text-sm text-muted-foreground">Your activity will appear here after your first practice session.</p>}</div></Card></div>
 </div>
}
function Metric({icon:Icon,label,value,note}:{icon:React.ComponentType<{size?:number}>;label:string;value:string;note:string}){return <Card className="p-4"><Icon size={18}/><p className="mt-4 text-xs font-extrabold uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></Card>}
function Plan({n,title,desc,to}:{n:string;title:string;desc:string;to:string}){return <Link to={to} className="focus-ring rounded-lg border border-border p-4 hover:bg-muted/50"><span className="text-xs font-black text-secondary">{n}</span><p className="mt-2 font-extrabold">{title}</p><p className="mt-1 text-sm text-muted-foreground">{desc}</p></Link>}
