import { useState } from 'react'
import { Check, Plus, Save, Trash2, Upload } from 'lucide-react'
import { Button, Card, Field, fieldClass } from '../components/ui'
import { useApp } from '../context/AppContext'
import { experiences, industries, roles, type Project } from '../lib/platform'
import usePageMeta from '../lib/usePageMeta'
export default function OnboardingPage(){
 usePageMeta('Preparation Context — PrepKite','Build the candidate context that powers personalized interview preparation.')
 const {user,profile,updateProfile,toast}=useApp(); if(!user||!profile)return null
 const [form,setForm]=useState(profile); const [saved,setSaved]=useState(false)
 const set=(k:keyof typeof form,v:any)=>setForm({...form,[k]:v})
 const add=()=>set('projects',[...form.projects,{name:'',tools:'',description:'',contribution:'',challenge:'',result:''}])
 const updateProject=(i:number,k:keyof Project,v:string)=>set('projects',form.projects.map((p,idx)=>idx===i?{...p,[k]:v}:p))
 const save=()=>{updateProfile(form);setSaved(true);toast({title:'Preparation context saved',description:'Dashboard, questions and practice now use this profile.',variant:'success'});window.setTimeout(()=>setSaved(false),2500)}
 return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div><p className="section-kicker">Preparation context</p><h1 className="display-font mt-2 text-4xl font-semibold">Build the interview around you.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Your role, company, skills and projects shape the question mix. Nothing here is a hiring decision; it is a preparation workspace.</p></div>
 <div className="mt-7 space-y-6"><Card><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-accent font-black">1</span><div><h2 className="font-extrabold">Your starting point</h2><p className="text-sm text-muted-foreground">The essentials used to shape language and level.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Name" htmlFor="p-name"><input id="p-name" className={fieldClass} value={form.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Education" htmlFor="education"><input id="education" className={fieldClass} value={form.education} onChange={e=>set('education',e.target.value)} placeholder="B.Com, B.E., MBA…"/></Field><Field label="Experience level" htmlFor="experience"><select id="experience" className={fieldClass} value={form.experience} onChange={e=>set('experience',e.target.value)}>{experiences.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Skills" htmlFor="skills"><input id="skills" className={fieldClass} value={form.skills} onChange={e=>set('skills',e.target.value)} placeholder="SQL, Excel, Python, Power BI"/></Field></div></Card>
 <Card><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-accent font-black">2</span><div><h2 className="font-extrabold">Target interview</h2><p className="text-sm text-muted-foreground">Company + role organize the preparation plan.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Field label="Target role" htmlFor="role"><select id="role" className={fieldClass} value={form.role} onChange={e=>set('role',e.target.value)}>{roles.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Target company" htmlFor="company"><input id="company" list="companies" className={fieldClass} value={form.company} onChange={e=>set('company',e.target.value)} placeholder="Search or type company"/><datalist id="companies"><option value="TCS"/><option value="Infosys"/><option value="Accenture"/><option value="Amazon"/><option value="Deloitte"/><option value="Zoho"/></datalist></Field><Field label="Industry" htmlFor="industry"><select id="industry" className={fieldClass} value={form.industry} onChange={e=>set('industry',e.target.value)}>{industries.map(x=><option key={x}>{x}</option>)}</select></Field></div></Card>
 <Card><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-accent font-black">3</span><div><h2 className="font-extrabold">Projects to talk about</h2><p className="text-sm text-muted-foreground">Project evidence becomes project questions and follow-ups.</p></div></div><Button variant="outline" onClick={add}><Plus size={16}/> Add project</Button></div><div className="mt-5 space-y-5">{form.projects.map((p,i)=><div key={i} className="rounded-xl border border-border p-5"><div className="flex items-center justify-between"><p className="font-extrabold">Project {i+1}</p><button className="focus-ring rounded-lg p-2 text-muted-foreground hover:bg-muted" onClick={()=>set('projects',form.projects.filter((_,idx)=>idx!==i))} aria-label={`Remove project ${i+1}`}><Trash2 size={17}/></button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Project name" htmlFor={`pn${i}`}><input id={`pn${i}`} className={fieldClass} value={p.name} onChange={e=>updateProject(i,'name',e.target.value)}/></Field><Field label="Tools / technology" htmlFor={`pt${i}`}><input id={`pt${i}`} className={fieldClass} value={p.tools} onChange={e=>updateProject(i,'tools',e.target.value)}/></Field><Field label="Description and purpose" htmlFor={`pd${i}`}><textarea id={`pd${i}`} className={`${fieldClass} min-h-24 py-3`} value={p.description} onChange={e=>updateProject(i,'description',e.target.value)}/></Field><Field label="Your contribution" htmlFor={`pc${i}`}><textarea id={`pc${i}`} className={`${fieldClass} min-h-24 py-3`} value={p.contribution} onChange={e=>updateProject(i,'contribution',e.target.value)}/></Field><Field label="Challenge" htmlFor={`pch${i}`}><textarea id={`pch${i}`} className={`${fieldClass} min-h-20 py-3`} value={p.challenge} onChange={e=>updateProject(i,'challenge',e.target.value)}/></Field><Field label="Result / lesson" htmlFor={`pr${i}`}><textarea id={`pr${i}`} className={`${fieldClass} min-h-20 py-3`} value={p.result} onChange={e=>updateProject(i,'result',e.target.value)}/></Field></div></div>)}{!form.projects.length&&<div className="rounded-xl border border-dashed border-border p-7 text-center text-sm text-muted-foreground">Add your strongest project so interview follow-ups can be specific.</div>}</div></Card>
 <Card><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-accent font-black">4</span><div><h2 className="font-extrabold">Profile sources</h2><p className="text-sm text-muted-foreground">Paste public profile URLs or upload your resume later; PrepKite only uses information you provide.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="LinkedIn URL" htmlFor="linkedin"><input id="linkedin" className={fieldClass} value={form.linkedin||''} onChange={e=>set('linkedin',e.target.value)} placeholder="https://www.linkedin.com/in/…"/></Field><Field label="Naukri URL" htmlFor="naukri"><input id="naukri" className={fieldClass} value={form.naukri||''} onChange={e=>set('naukri',e.target.value)} placeholder="https://www.naukri.com/…"/></Field><div className="rounded-lg border border-dashed border-border p-4 md:col-span-2"><div className="flex items-center gap-3"><Upload size={18}/><div><p className="text-sm font-bold">Resume file</p><p className="text-xs text-muted-foreground">For this offline version, record the file name; parsing can be connected to a backend later.</p></div></div><input type="file" accept=".pdf,.doc,.docx" className="mt-3 text-sm" onChange={e=>set('resumeName',e.target.files?.[0]?.name||'')}/>{form.resumeName&&<p className="mt-2 text-xs font-bold text-secondary">Selected: {form.resumeName}</p>}</div></div></Card>
 <div className="sticky bottom-4 flex justify-end"><Button onClick={save}><Save size={16}/>{saved?<><Check size={16}/> Saved</>:'Save and open dashboard'}</Button></div>
 </div></div>
}
