import { BarChart3, CalendarCheck2, Flame, Target, TrendingDown, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge, Button, Card } from '../components/ui'
import { useApp } from '../context/AppContext'
import { getStats, readiness } from '../lib/platform'
import usePageMeta from '../lib/usePageMeta'
export default function ProgressPage(){
 usePageMeta('Progress — PrepKite','Weekly preparation trends, attendance and skill improvement.')
 const {user,profile}=useApp();if(!user||!profile)return null;const stats=getStats(user.id),r=readiness(user.id),skills=r.skills;const weak=skills.slice().sort((a,b)=>a.value-b.value).slice(0,4);const strong=skills.slice().sort((a,b)=>b.value-a.value).slice(0,4)
 return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div><p className="section-kicker">Progress intelligence</p><h1 className="display-font mt-2 text-4xl font-semibold">See how your preparation changes week by week.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">No fake readiness number: your signals come from recorded attendance, question practice, mock sessions and scored answers.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BarChart3} label="Readiness signal" value={`${r.score}%`}/><Metric icon={CalendarCheck2} label="Attendance" value={`${stats.attendanceDays}`}/><Metric icon={Flame} label="Current streak" value={`${stats.streak} days`}/><Metric icon={Target} label="Weekly actions" value={`${stats.weeklyCount}`}/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><p className="section-kicker">Skill map</p><h2 className="mt-1 text-xl font-extrabold">Where your practice is landing</h2><div className="mt-5 space-y-5">{skills.map(s=><div key={s.skill}><div className="flex justify-between text-sm"><span className="font-bold">{s.skill}</span><span>{s.value}% · {s.count} attempts</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-secondary" style={{width:`${s.value}%`}}/></div></div>)}</div></Card><Card><p className="section-kicker">Weekly review</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-accent/50 p-5"><TrendingUp size={19}/><p className="mt-3 text-xs font-black uppercase tracking-[.12em]">Strong signals</p><p className="mt-2 text-sm leading-6">{strong.map(x=>x.skill).join(', ')}</p></div><div className="rounded-xl bg-muted p-5"><TrendingDown size={19}/><p className="mt-3 text-xs font-black uppercase tracking-[.12em]">Improve next</p><p className="mt-2 text-sm leading-6">{weak.map(x=>x.skill).join(', ')}</p></div></div><div className="mt-5 border-t border-border pt-5"><h2 className="font-extrabold">Next-week recommendation</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Spend the first two sessions on {weak[0]?.skill||'your weakest skill'}, one session on project follow-ups, and finish with a mock interview.</p><Link to="/practice"><Button className="mt-4">Start improvement plan</Button></Link></div></Card></div></div>
}
function Metric({icon:Icon,label,value}:{icon:React.ComponentType<{size?:number}>;label:string;value:string}){return <Card className="p-4"><Icon size={18}/><p className="mt-3 text-xs font-black uppercase tracking-[.12em] text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></Card>}
