import { useMemo, useState } from 'react'
import { Bookmark, BookmarkCheck, Search, Sparkles } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { Badge, Button, Card, EmptyState, fieldClass } from '../components/ui'
import { useApp } from '../context/AppContext'
import { addActivity, getQuestionBank, getSaved, toggleSaved } from '../lib/platform'
import usePageMeta from '../lib/usePageMeta'
export default function QuestionsPage(){
 usePageMeta('Question Intelligence — PrepKite','Role, skill and company-aware interview question practice.')
 const {user,profile,toast}=useApp(); const [params,setParams]=useSearchParams(); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [companyOnly,setCompanyOnly]=useState(false); if(!user||!profile)return null
 const bank=useMemo(()=>getQuestionBank(profile),[profile]); const saved=getSaved(user.id); const selected=params.get('open')||bank[0]?.id; const filtered=bank.filter(q=>(filter==='All'||q.category===filter||q.skill===filter)&&(!companyOnly||!!profile.company)&&`${q.title} ${q.prompt} ${q.skill}`.toLowerCase().includes(query.toLowerCase()))
 const q=filtered.find(x=>x.id===selected)||filtered[0]
 const save=(id:string)=>{const now=toggleSaved(user.id,id);toast({title:now?'Saved question':'Removed from saved',description:'Your study list is stored in this browser.',variant:'success'})}
 const practiced=()=>{if(!q)return;addActivity(user.id,{type:'question',label:`Practiced: ${q.title}`,skill:q.skill,company:profile.company||undefined,score:80});toast({title:'Question practice recorded',description:'Your progress signal was updated.',variant:'success'})}
 const cats=['All',...Array.from(new Set(bank.map(x=>x.category))),...Array.from(new Set(bank.map(x=>x.skill))).slice(0,8)]
 return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">Question intelligence</p><h1 className="display-font mt-2 text-4xl font-semibold">Practice what your role can actually ask.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{profile.company?`${profile.company} · `:''}{profile.role} questions are mixed across role knowledge, practical tasks, projects and behavioral follow-ups. Company themes are preparation signals, not guarantees of what an interviewer will ask.</p></div><Badge tone="primary"><Sparkles size={14} className="mr-1"/> Personalized bank</Badge></div>
 <div className="mt-7 grid gap-3 rounded-xl border border-border bg-card p-4 md:grid-cols-[1fr_180px_auto]"><div className="relative"><Search size={17} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input className={`${fieldClass} pl-10`} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search skill, question, topic"/></div><select className={fieldClass} value={filter} onChange={e=>setFilter(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select><Button variant={companyOnly?'secondary':'outline'} onClick={()=>setCompanyOnly(!companyOnly)}>Company focus {companyOnly?'On':'Off'}</Button></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_390px]"><section className="space-y-3">{filtered.map(item=><button key={item.id} onClick={()=>setParams({open:item.id})} className={`focus-ring w-full rounded-xl border bg-card p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${item.id===q?.id?'border-secondary':'border-border'}`}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><Badge tone="muted">{item.category}</Badge><Badge tone="primary">{item.skill}</Badge></div><h2 className="mt-3 font-extrabold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.prompt}</p></div>{saved.includes(item.id)?<BookmarkCheck size={19} className="shrink-0 text-secondary"/>:<Bookmark size={19} className="shrink-0 text-muted-foreground"/>}</div></button>)}{!filtered.length&&<EmptyState icon={Search} title="No matching questions" description="Try another skill or clear the search."/>}</section>
 <aside>{q?<Card className="sticky top-24"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">Selected question</p><h2 className="mt-2 text-xl font-extrabold">{q.title}</h2></div><button className="focus-ring rounded-lg p-2 hover:bg-muted" onClick={()=>save(q.id)} aria-label="Save question">{saved.includes(q.id)?<BookmarkCheck className="text-secondary"/>:<Bookmark/>}</button></div><div className="mt-5 rounded-xl bg-muted/60 p-4"><p className="text-xs font-black uppercase tracking-[.12em]">Practical version</p><p className="mt-2 text-sm leading-6">{q.practical}</p></div><div className="mt-5 space-y-3"><div><p className="text-xs font-black uppercase tracking-[.12em] text-muted-foreground">Interview approach</p><p className="mt-1 text-sm leading-6">State assumptions → solve step by step → validate the result → explain one trade-off.</p></div><div><p className="text-xs font-black uppercase tracking-[.12em] text-muted-foreground">Likely follow-up</p><p className="mt-1 text-sm leading-6">Why did you choose that approach, and what would you change if the data or requirements changed?</p></div></div><Button className="mt-5 w-full" onClick={practiced}>Mark practiced <BookmarkCheck size={16}/></Button></Card>:null}</aside></div></div>
}
