import { useEffect, useRef, useState } from 'react'
import { BarChart3, BookOpen, Building2, CalendarCheck2, ChevronRight, Gauge, LayoutDashboard, LogIn, Menu, Mic2, Sparkles, Swords, UserRoundCheck, UserRound, X } from 'lucide-react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { initials } from '../lib/utils'
const navGroups=[
 {label:'Workspace',items:[{to:'/dashboard',label:'Dashboard',icon:LayoutDashboard},{to:'/prepare',label:'Prepare',icon:UserRoundCheck},{to:'/questions',label:'Question Intelligence',icon:BookOpen},{to:'/companies',label:'Company Intelligence',icon:Building2}]},
 {label:'Interview Lab',items:[{to:'/practice',label:'Practice Arena',icon:Gauge},{to:'/mock',label:'Mock Interview',icon:Mic2},{to:'/challenges',label:'Challenges',icon:Swords}]},
 {label:'Growth',items:[{to:'/progress',label:'Progress & Readiness',icon:BarChart3},{to:'/profile',label:'Candidate Profile',icon:UserRound}]}
]
export default function AppShell({children}:{children:React.ReactNode}){
 const [mobileOpen,setMobileOpen]=useState(false);const {user,profile}=useApp();const location=useLocation();const trigger=useRef<HTMLButtonElement>(null);const isPublic=location.pathname==='/'||location.pathname==='/auth'
 useEffect(()=>{setMobileOpen(false)},[location.pathname]);useEffect(()=>{if(!mobileOpen)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setMobileOpen(false)};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[mobileOpen])
 if(isPublic)return <>{children}</>
 const close=()=>{setMobileOpen(false);window.setTimeout(()=>trigger.current?.focus(),0)}
 return <div className="min-h-screen bg-background">
  <aside className="fixed inset-y-0 left-0 z-40 hidden w-72 border-r border-border bg-card px-4 py-5 lg:block"><Brand/><div className="mt-7 space-y-6">{navGroups.map(group=><nav key={group.label} aria-label={group.label}><p className="px-3 pb-2 text-[10px] font-black uppercase tracking-[.18em] text-muted-foreground">{group.label}</p><div className="space-y-1">{group.items.map(({to,label,icon:Icon})=><NavLink key={to} to={to} className={({isActive})=>`focus-ring flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold transition ${isActive?'bg-primary text-primary-foreground shadow-sm':'text-muted-foreground hover:bg-accent hover:text-accent-foreground'}`}><Icon size={18}/>{label}</NavLink>)}</div></nav>)}</div><div className="absolute inset-x-4 bottom-5 rounded-xl bg-primary p-4 text-primary-foreground"><p className="text-xs font-extrabold uppercase tracking-[.13em] text-primary-foreground/70">Today’s focus</p><p className="mt-2 text-sm font-bold">{profile?.company?`${profile.company} · ${profile.role}`:'Finish your interview profile.'}</p><Link to={profile?.company?'/practice':'/onboarding'} className="focus-ring mt-3 inline-flex items-center gap-1 text-sm font-extrabold underline underline-offset-4">{profile?.company?'Open practice':'Complete profile'}<ChevronRight size={15}/></Link></div></aside>
  <header className="sticky top-0 z-30 border-b border-border bg-background/95 backdrop-blur lg:ml-72"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><button ref={trigger} type="button" aria-label="Open navigation" aria-expanded={mobileOpen} onClick={()=>setMobileOpen(true)} className="focus-ring rounded-lg p-2 text-foreground hover:bg-accent lg:hidden"><Menu size={21}/></button><div className="hidden text-sm text-muted-foreground sm:block"><span className="font-bold text-foreground">PrepKite</span><span className="mx-2">/</span>{profile?.role||'Interview workspace'}{profile?.company?<><span className="mx-2">·</span>{profile.company}</>:null}</div><Link to={user?'/profile':'/auth'} className="focus-ring inline-flex items-center gap-2 rounded-lg p-1.5 text-sm font-bold text-foreground hover:bg-accent"><span className="grid h-8 w-8 place-items-center rounded-full bg-accent text-xs font-extrabold text-accent-foreground">{user?initials(user.name):<LogIn size={15}/>}</span><span className="hidden sm:inline">{user?.name||'Sign in'}</span></Link></div></header>
  {mobileOpen&&<div className="fixed inset-0 z-50 lg:hidden"><button type="button" aria-label="Close navigation" className="absolute inset-0 bg-primary/35" onClick={close}/><aside aria-label="Mobile navigation" className="relative h-full w-80 border-r border-border bg-card p-5 shadow-xl"><div className="flex items-center justify-between"><Brand/><button type="button" aria-label="Close navigation" onClick={close} className="focus-ring rounded-lg p-2 hover:bg-accent"><X size={20}/></button></div><div className="mt-8 space-y-6">{navGroups.map(group=><nav key={group.label} aria-label={group.label}><p className="px-3 pb-2 text-[10px] font-black uppercase tracking-[.18em] text-muted-foreground">{group.label}</p><div className="space-y-1">{group.items.map(({to,label,icon:Icon})=><NavLink key={to} to={to} onClick={close} className={({isActive})=>`focus-ring flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-bold ${isActive?'bg-accent text-accent-foreground':'text-muted-foreground hover:bg-accent hover:text-accent-foreground'}`}><Icon size={18}/>{label}</NavLink>)}</div></nav>)}</div></aside></div>}
  <main className="lg:ml-72">{children}</main>
 </div>
}
function Brand(){return <Link to="/" className="focus-ring inline-flex items-center gap-2 rounded-lg"><span className="grid h-10 w-10 rotate-45 place-items-center rounded-[14px] bg-primary shadow-sm"><Sparkles size={17} className="-rotate-45 text-primary-foreground"/></span><span><span className="block text-lg font-extrabold tracking-tight text-foreground">PrepKite</span><span className="block text-[9px] font-black uppercase tracking-[.18em] text-secondary">Interview Intelligence</span></span></Link>}
